### ISSUE TITLE
请问PatchAssemblies时出现AssemblyResolutionException异常是什么原因?

### ISSUE THREAD

**Issue by LoneWindG** [Misaka-Mikoto-Tech/UnityScriptHotReload#1]
PatchAssemblies时写入patchDll时出现异常;
xxxx.audio.runtime是热重载的程序集引用的程序集, 此程序集和热重载的程序集都是通过AssemblyDefinition定义的程序集;
查看编译的输出目录Temp\ScriptHotReload\tmp也存在xxxx.audio.runtime这个程序集;

异常信息及堆栈如下:
```c#
[Exception] AssemblyResolutionException: Failed to resolve assembly: 'xxxx.audio.runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
BaseAssemblyResolver.Resolve() at <d9c08e98cbab4d61a472a54d4ef82867>:0
BaseAssemblyResolver.Resolve() at <d9c08e98cbab4d61a472a54d4ef82867>:0
DefaultAssemblyResolver.Resolve() at <d9c08e98cbab4d61a472a54d4ef82867>:0
MetadataResolver.Resolve() at <d9c08e98cbab4d61a472a54d4ef82867>:0
ModuleDefinition.Resolve() at <d9c08e98cbab4d61a472a54d4ef82867>:0
TypeReference.Resolve() at <d9c08e98cbab4d61a472a54d4ef82867>:0
Mixin.CheckedResolve() at <d9c08e98cbab4d61a472a54d4ef82867>:0
MetadataBuilder.GetConstantType() at <d9c08e98cbab4d61a472a54d4ef82867>:0
MetadataBuilder.AddConstant() at <d9c08e98cbab4d61a472a54d4ef82867>:0
MetadataBuilder.AddParameter() at <d9c08e98cbab4d61a472a54d4ef82867>:0
MetadataBuilder.AddParameters() at <d9c08e98cbab4d61a472a54d4ef82867>:0
MetadataBuilder.AddMethod() at <d9c08e98cbab4d61a472a54d4ef82867>:0
MetadataBuilder.AddMethods() at <d9c08e98cbab4d61a472a54d4ef82867>:0
MetadataBuilder.AddType() at <d9c08e98cbab4d61a472a54d4ef82867>:0
MetadataBuilder.AddNestedTypes() at <d9c08e98cbab4d61a472a54d4ef82867>:0
MetadataBuilder.AddType() at <d9c08e98cbab4d61a472a54d4ef82867>:0
MetadataBuilder.AddTypes() at <d9c08e98cbab4d61a472a54d4ef82867>:0
MetadataBuilder.BuildTypes() at <d9c08e98cbab4d61a472a54d4ef82867>:0
MetadataBuilder.BuildModule() at <d9c08e98cbab4d61a472a54d4ef82867>:0
MetadataBuilder.BuildMetadata() at <d9c08e98cbab4d61a472a54d4ef82867>:0
ModuleWriter+<>c.<BuildMetadata>b__2_0() at <d9c08e98cbab4d61a472a54d4ef82867>:0
ModuleDefinition.Read[TItem,TRet]() at <d9c08e98cbab4d61a472a54d4ef82867>:0
ModuleWriter.BuildMetadata() at <d9c08e98cbab4d61a472a54d4ef82867>:0
ModuleWriter.Write() at <d9c08e98cbab4d61a472a54d4ef82867>:0
ModuleWriter.WriteModule() at <d9c08e98cbab4d61a472a54d4ef82867>:0
ModuleDefinition.Write() at <d9c08e98cbab4d61a472a54d4ef82867>:0
AssemblyDefinition.Write() at <d9c08e98cbab4d61a472a54d4ef82867>:0

GenPatchAssemblies.OnScriptCompileSuccess() at /__Scripts/MainEditor/HotReload/Editor/PatchAssemblies.cs:88
87:   string patchDll = string.Format(kPatchDllPathFormat, assNameNoExt, patchNo);
-->88:   newAssDef.Write(patchDll, writeParam);
90:   methodsToHook.Add(assName, assBuilder.assemblyData.methodModified.Values.ToList());

CompileScript.EditorApplication_Update() at /__Scripts/MainEditor/HotReload/Editor/CompileScript.cs:93
91:   {
92:       s_CompileRequested = false;
-->93:       OnCompileSuccess?.Invoke(compileStatus);
95:       if (compileStatus == CompileStatus.Idle)

EditorApplication.Internal_CallUpdateFunctions() at <f6b8f61e600242f784ecb4a62a41289e>:0
```
[使用代码的最后提交](https://github.com/Misaka-Mikoto-Tech/UnityScriptHotReload/commit/b83d8a64f2fd5070427b43ae3a0ca95622e72bcf)

**Comment by 526077247** [comment]
![ZY1W1EHJV58}ADLIYLL2UIH](https://user-images.githubusercontent.com/45992829/207550758-8293cd1d-daf6-49cd-a64b-2ba1ce15ee9e.png)
+1

**Comment by Misaka-Mikoto-Tech** [comment]
我先查一下

**Comment by Misaka-Mikoto-Tech** [comment]
> PatchAssemblies时写入patchDll时出现异常; xxxx.audio.runtime是热重载的程序集引用的程序集, 此程序集和热重载的程序集都是通过AssemblyDefinition定义的程序集; 查看编译的输出目录Temp\ScriptHotReload\tmp也存在xxxx.audio.runtime这个程序集;
> 
> 异常信息及堆栈如下:
> 
> ```cs
> [Exception] AssemblyResolutionException: Failed to resolve assembly: 'xxxx.audio.runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
> BaseAssemblyResolver.Resolve() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> BaseAssemblyResolver.Resolve() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> DefaultAssemblyResolver.Resolve() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> MetadataResolver.Resolve() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> ModuleDefinition.Resolve() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> TypeReference.Resolve() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> Mixin.CheckedResolve() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> MetadataBuilder.GetConstantType() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> MetadataBuilder.AddConstant() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> MetadataBuilder.AddParameter() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> MetadataBuilder.AddParameters() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> MetadataBuilder.AddMethod() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> MetadataBuilder.AddMethods() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> MetadataBuilder.AddType() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> MetadataBuilder.AddNestedTypes() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> MetadataBuilder.AddType() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> MetadataBuilder.AddTypes() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> MetadataBuilder.BuildTypes() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> MetadataBuilder.BuildModule() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> MetadataBuilder.BuildMetadata() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> ModuleWriter+<>c.<BuildMetadata>b__2_0() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> ModuleDefinition.Read[TItem,TRet]() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> ModuleWriter.BuildMetadata() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> ModuleWriter.Write() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> ModuleWriter.WriteModule() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> ModuleDefinition.Write() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> AssemblyDefinition.Write() at <d9c08e98cbab4d61a472a54d4ef82867>:0
> 
> GenPatchAssemblies.OnScriptCompileSuccess() at /__Scripts/MainEditor/HotReload/Editor/PatchAssemblies.cs:88
> 87:   string patchDll = string.Format(kPatchDllPathFormat, assNameNoExt, patchNo);
> -->88:   newAssDef.Write(patchDll, writeParam);
> 90:   methodsToHook.Add(assName, assBuilder.assemblyData.methodModified.Values.ToList());
> 
> CompileScript.EditorApplication_Update() at /__Scripts/MainEditor/HotReload/Editor/CompileScript.cs:93
> 91:   {
> 92:       s_CompileRequested = false;
> -->93:       OnCompileSuccess?.Invoke(compileStatus);
> 95:       if (compileStatus == CompileStatus.Idle)
> 
> EditorApplication.Internal_CallUpdateFunctions() at <f6b8f61e600242f784ecb4a62a41289e>:0
> ```
> 
> [使用代码的最后提交](https://github.com/Misaka-Mikoto-Tech/UnityScriptHotReload/commit/b83d8a64f2fd5070427b43ae3a0ca95622e72bcf)

https://github.com/Misaka-Mikoto-Tech/UnityScriptHotReload/commit/fc03b7f307787ace45437c5340e7380399dffc71
我增加了一个asmdef，测试没问题，你能给一个可以重现的测试用例吗？

**Comment by LoneWindG** [comment]
> 我先查一下

测试了下会导致异常的热重载程序集的代码:
 ```cs
using XXXX.Audio;
using UnityEngine;
using UnityEngine.UI;

//热重载程序集仅包含这一个文件, 代码执行方式为在一个MonoBehaviour.Start()内反射创建了一个HotReloadScript对象并反射调用了Awake方法

//测试结果如下(根据对xxx.audio.runtime的代码块引用保留情况):
//仅保留代码块1, 无异常
//仅保留代码块2, 无异常
//仅保留代码块3, 无异常
//保留代码块4&5, 出现AssemblyResolutionException
//保留代码块4但注释代码块5, 出现AssemblyResolutionException

public class HotReloadScript
{
    private Text _text;

    public void Awake()
    {
        var main = GameObject.Find("/Canvas");
        var btn = main.GetComponentInChildren<Button>();
        //{
        //    //引用xxx.audio.runtime的代码块1
        //    var btnGo = btn.gameObject;
        //    Object.DestroyImmediate(btn);
        //    btn = btnGo.AddComponent<AudioButton>();
        //}
        btn.onClick.AddListener(OnTestHotReload);
        _text = main.GetComponentInChildren<Text>();
    }

    private void OnTestHotReload()
    {
        //热重载的方法体, 每次测试时热重载只会改变这个字符串, 不会改动其他代码
        _text.text = "测试文本1";
    }
}

//没有任何其他代码引用到这个类型
public static class Sound
{
    ////引用xxx.audio.runtime的代码块2, 指整个方法
    //public static void PlaySound2()
    //{
    //    AudioManager.Instace.PlaySound(AudioSourceType.AS_Operation, "");
    //}

    ////引用xxx.audio.runtime的代码块3, 指整个方法
    //public static void PlaySound3(string soundName, AudioSourceType sourceType, bool forceWaitStop)
    //{
    //     AudioManager.Instace.PlaySound(sourceType, soundName, 0.5f, forceWaitStop: forceWaitStop);
    //}

    //引用xxx.audio.runtime的代码块4, 指整个方法
    public static void PlaySound4(string soundName = "UI_btn_tongyongdianji", AudioSourceType sourceType = AudioSourceType.AS_Operation, bool forceWaitStop = true)
    {
        //{
        //    //引用xxx.audio.runtime的代码块5
        //    AudioManager.Instace.PlaySound(sourceType, soundName, fadeDuration: sourceType == AudioSourceType.AS_Bgm ? 0.5f : 0, forceWaitStop: forceWaitStop);
        //}
    }
}


 ```

**Comment by Misaka-Mikoto-Tech** [comment]
最好提供一个可以重现问题的工程压缩包

**Comment by LoneWindG** [comment]
> 最好提供一个可以重现问题的工程压缩包

好的, 我这边周一到公司了整理下

**Comment by LoneWindG** [comment]
> 最好提供一个可以重现问题的工程压缩包

实测应该是热重载程序集的方法可选参数有引用其他程序集时, 写入patch的dll就会报找不到引用的这个程序集的问题;
[TestHotReload.zip](https://github.com/Misaka-Mikoto-Tech/UnityScriptHotReload/files/10255407/TestHotReload.zip)

**Comment by Misaka-Mikoto-Tech** [comment]
> > 最好提供一个可以重现问题的工程压缩包
> 
> 实测应该是热重载程序集的方法可选参数有引用其他程序集时, 写入patch的dll就会报找不到引用的这个程序集的问题; [TestHotReload.zip](https://github.com/Misaka-Mikoto-Tech/UnityScriptHotReload/files/10255407/TestHotReload.zip)

https://github.com/Misaka-Mikoto-Tech/UnityScriptHotReload/commit/0a3bda774074c8368c59af4dca70e1ec66e5f20f
已修正，你再试一下

**Comment by LoneWindG** [comment]
> > > 最好提供一个可以重现问题的工程压缩包
> > 
> > 
> > 实测应该是热重载程序集的方法可选参数有引用其他程序集时, 写入patch的dll就会报找不到引用的这个程序集的问题; [TestHotReload.zip](https://github.com/Misaka-Mikoto-Tech/UnityScriptHotReload/files/10255407/TestHotReload.zip)
> 
> [0a3bda7](https://github.com/Misaka-Mikoto-Tech/UnityScriptHotReload/commit/0a3bda774074c8368c59af4dca70e1ec66e5f20f) 已修正，你再试一下

OK, 测试没问题了
